#!C:\WinP\bd312\bu\WPy64-31230\python-3.12.3.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
